export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_POST_DETAILS = 'RECEIVE_POST_DETAILS'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const UP_VOTE_POST = 'UP_VOTE_POST'

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT'

export const FILTER_ON_SCORE = 'FILTER_ON_SCORE'
